### Importing libraries

In [39]:
import pandas as pd
import numpy as np
import nltk as nl
import matplotlib.pyplot as plt
import seaborn

In [40]:
df = pd.read_json('News_Category_Dataset_v3.json', lines= True)
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [41]:
df.isna().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [42]:
df = df.drop_duplicates()

In [43]:
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [44]:
# Dropping unwanted columns for this

df = df.drop(columns= ['link','authors'])
df

,headline,category,short_description,date
0,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,2022-09-23
1,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,2022-09-23
2,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",2022-09-23
3,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",2022-09-23
4,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,2022-09-22
...,...,...,...,...
209522,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,2012-01-28
209523,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",2012-01-28
209524,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",2012-01-28
209525,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,2012-01-28
209526,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,2012-01-28

In [45]:
from tfr import preprocessing

prep = preprocessing()

prep.fit_transform(df['headline'])

['4-',
 ',',
 '23(.17-23)',
 '(.17-23)',
 '--',
 '4:',
 '',
 '’',
 '',
 "'",
 '',
 "'",
 '4',
 '$200,000',
 '.6',
 '437-80',
 "''-",
 ',-,89',
 '4-',
 '3',
 '-',
 '..',
 '',
 '',
 '‘’:',
 '',
 ',',
 '',
 "''''",
 "'-'60",
 "'''",
 '2020’',
 '',
 '',
 "'-'",
 '',
 '-',
 '’’',
 '',
 "'2099'",
 '',
 "'63",
 '',
 "''",
 '.:',
 ',',
 '--',
 "''",
 "'",
 '$1002’',
 '$100,000',
 ',',
 '-',
 ',',
 '',
 ':',
 '..2',
 '-,,',
 '3-',
 '‘’',
 '.',
 '',
 ',,9/11',
 '',
 ",''",
 '',
 "''--",
 '..1,',
 ',',
 '9/11,',
 '9/11..21',
 "'",
 '',
 ',--',
 "':'23",
 "''",
 '',
 ';',
 '',
 '-.',
 "'':'",
 '',
 "''-",
 "'’,",
 '',
 "'':''",
 "'",
 "'",
 '32',
 '-',
 '1%,',
 '',
 ',',
 ',',
 '',
 '-2',
 ',4,671',
 "''",
 ',,$400',
 '',
 '..:,',
 "'''",
 '‘’',
 '',
 '',
 '',
 '-',
 ":'",
 "'‘’",
 "'",
 '',
 '',
 "'':','",
 '',
 "'2",
 '9:',
 '',
 ':',
 ',',
 "'",
 '',
 '..315,000',
 '',
 '-?',
 "''",
 "',",
 '',
 "'90—",
 ".'''",
 "'1998",
 "'",
 '‘&’--',
 '3.',
 '',
 '6’()',
 "'':",
 '-.6',
 "''",
 ',',
 '’,4-',
 '.?',
 "''",
 "'''",
 '',
 '',
 "1,000''",
 '2022:',
 '..',
 "''",
 '---:',
 ':',
 ".'':'!'",
 '---',
 '6,',
 '..',
 "''",
 "''",
 '--:',
 "',",
 ':',
 '6,..',
 '',
 '',
 '.',
 '’',
 "',-",
 ',,',
 '.',
 '.$132',
 '',
 '',
 "''-",
 '',
 ",',82",
 "''",
 "'''-",
 ',,',
 "'",
 '',
 "'",
 ':9,000',
 ',,',
 "'-",
 '',
 '',
 '-’',
 ',’-,74',
 '‘’‘’$20.1',
 '’',
 "',",
 "',",
 ',,95',
 '',
 "'.",
 '',
 '',
 '',
 '',
 '',
 '',
 ".''34-",
 ',',
 '.,',
 '11-',
 "''",
 '',
 '',
 "484,000''-",
 '$50',
 "','",
 '',
 "'",
 '--',
 '’-',
 '',
 '',
 '-',
 ',',
 "''49",
 '3',
 '',
 "'",
 '.',
 '8-',
 '‘’.1;‘’',
 ':41',
 "'!''",
 "','",
 "''21,000",
 '',
 '',
 '',
 '',
 "''-",
 '‘’',
 '$2,,..',
 "',",
 '’',
 ',-19',
 '',
 '‘’',
 ':',
 '..',
 '$45',
 ',2024',
 "'''3",
 '-',
 '',
 '',
 '',
 '’--',
 ':’',
 "''-'''",
 ":3-'",
 '$4.65',
 '3',
 "’'':",
 '',
 '',
 '‘,!’',
 ',',
 '57:,',
 '’‘’$30.1',
 "'''",
 '',
 '..3',
 '120,',
 '',
 'ä',
 "''",
 '',
 "5-'''",
 '',
 "—'",
 ':.6',
 '5,8',
 "'**''..",
 '',
 ".'.",
 '4',
 "''",
 '’?’.',
 "'",
 '',
 '',
 "'80''",
 '’',
 '',
 '',
 "'",
 ':’‘’',
 "''-",
 ',',
 '',
 "'1%,",
 "'2024",
 '9-,',
 '’',
 ',',
 "4'-'",
 '28',
 '',
 ":'",
 '‘-’.1$23',
 '',
 '--',
 '.6',
 '',
 "'",
 "-'''",
 '.62',
 "''",
 '',
 ":''50''",
 '',
 "'",
 'é3--',
 "'''",
 '',
 '',
 "2'",
 '.',
 '?',
 "''5",
 '',
 '.:',
 '14',
 "'4,000'''''",
 ',‘’‘&’,83',
 '',
 ',,35',
 ".'",
 ",''",
 ',',
 "'''$6.1",
 "','",
 "'.'.",
 "'''",
 '6--3',
 '',
 '—’',
 ',',
 ".'.",
 ":''",
 '23(16-22)',
 '195',
 '9',
 '2',
 ',-',
 "'':''",
 '',
 '',
 ',',
 "''",
 '$5’',
 "''1",
 "'.6,",
 "'90é'",
 '-',
 '4',
 "''-''",
 '',
 '',
 ':..‘’',
 "':",
 '-',
 '-',
 ",-'',28",
 '',
 "'''",
 '',
 "'",
 '',
 ":'',!'",
 '.6',
 "'':'''",
 '',
 "''.",
 '..-',
 '-',
 "'''",
 '',
 '.6:',
 ':',
 '',
 ',',
 '.6',
 '-',
 '',
 '‘’:',
 '',
 '2022',
 '',
 "''",
 "''",
 ":'",
 '',
 '‘’',
 '7',
 '-',
 '15',
 '.6,.',
 ',',
 '',
 '2024',
 "'..'':",
 '',
 '',
 "'''-",
 "'",
 '',
 ',',
 ',',
 "',",
 "''82",
 '?().',
 '3',
 '',
 ",'',97",
 '',
 '',
 '-',
 '-',
 ':',
 '’',
 ".'''",
 ",''",
 '.',
 "''",
 '',
 "'','-",
 ",&'",
 ',10,',
 ',',
 '',
 '23',
 '-',
 '-',
 "?'.",
 '(25-1)',
 '(25-1)',
 "'',",
 '‘’&‘’',
 '’17%,',
 "'''",
 "'',",
 "-'1-.6",
 "'",
 ',',
 "':'",
 "':",
 '’-',
 '',
 ',101,',
 "'90-",
 ",'2022",
 ',-2022',
 "'':'''",
 "'10--",
 "'",
 "':'**'",
 "2022:'''",
 ',,',
 '11-',
 ':',
 '',
 '20(18-24)',
 "'**'-",
 '',
 '.:',
 '',
 "'',-''",
 ':,',
 '',
 "2022:','''",
 '.‘’',
 "'!'",
 ',',
 '52',
 '',
 "'",
 '',
 "7.6'",
 '/',
 '́‘’’',
 '-2.6',
 "'",
 '’',
 '69%',
 '7',
 "-''",
 ",'",
 '-',
 ':',
 '‘’',
 "'':",
 ",,':",
 '’',
 '-195',
 ',',
 "'",
 '..6—',
 '-’',
 '(11-17)',
 '.,',
 "'",
 '10,',
 '20(11-17)',
 ',,4',
 '',
 "'''",
 '’10',
 "'''",
 "'''",
 "-''",
 ',.',
 '',
 "'",
 '',
 ',,',
 "'!'",
 ';',
 '',
 "':'20",
 "''",
 "'",
 "''",
 '',
 "'",
 '',
 "31'':",
 '4',
 "''",
 ',-',
 "''2020;,",
 '-19',
 '25(4-10)',
 "''.6",
 "''",
 "'''",
 '(4-10)',
 ',',
 "''''",
 "'-'",
 "'',",
 "'",
 ':',
 '1996',
 "-:'!'",
 "''",
 '',
 "','",
 "''",
 "'",
 "'",
 '',
 '',
 ",',,",
 '‘’4',
 "''&",
 '',
 "''''",
 ',',
 '--',
 "''",
 ".:'''",
 "',,46",
 '',
 '‘’',
 '14,',
 ',?',
 '',
 ".''",
 '',
 '(28-3)',
 '20(28-3)',
 '',
 '',
 ':',
 '’-',
 '‘’—',
 "'''",
 '4',
 ',',
 "‘’'!’",
 '—:,,',
 ".-,'.",
 "'--",
 "''''",
 '',
 "':,,",
 ",',",
 '1',
 '',
 '',
 ',$2',
 '’,',
 ',',
 "''',",
 "'-,'",
 '.',
 '',
 "-,''",
 ':',
 '',
 '',
 '',
 "''",
 '.6',
 "''",
 '11',
 '(21-27)',
 "''",
 '20(21-27)',
 '',
 '.',
 '‘’',
 "''",
 '-',
 "'",
 '...',
 '',
 "''",
 '’.1',
 ".':''",
 "'':.'",
 '',
 "','",
 '',
 "'''",
 "'''",
 '',
 ',130',
 ":..''",
 ",'",
 '',
 '',
 '‘’‘’',
 "''",
 '78,000',
 '',
 '',
 "'''",
 "'",
 "':",
 "145'':",
 ",550-''",
 "'''",
 "'''",
 '',
 '(14-20)',
 "'':",
 ':',
 '',
 '',
 "''.'.",
 "',",
 "'''",
 "-'''",
 ',-,',
 "50'",
 ':',
 '',
 ',’‘’',
 '’',
 '50',
 "''",
 "''",
 ':',
 ',',
 "''",
 '-',
 '---',
 "'':",
 ',',
 "''",
 "-9'''",
 '1,4,',
 "''",
 '',
 '’‘’‘.2’-',
 "13,10'':",
 ".''",
 '’',
 "'",
 '’’.?',
 "''",
 '.',
 '(7-13)',
 '20(7-13)',
 '',
 '',
 "'",
 "-2'",
 ',8,',
 '',
 ".:''''",
 '-19',
 '',
 '',
 '44',
 '',
 ",''-'",
 "',",
 ',,',
 ':',
 '-',
 '',
 '.6,',
 ".-19'",
 ',',
 "'",
 '30',
 '',
 '',
 "'",
 '..,',
 '7',
 '!',
 '',
 '-',
 "''",
 '',
 '',
 '',
 '',
 '',
 '428,000',
 '3',
 '',
 "''",
 '',
 "'''",
 '.-',
 '6',
 ':2021',
 '.',
 "..,',",
 ',,',
 "'",
 '‘’',
 '',
 "2022:'",
 '.',
 '..',
 ',..',
 '',
 ".'",
 '',
 ',',
 "''",
 ',',
 "..'-",
 '',
 '‘’.1,’',
 ',',
 ':?',
 '2',
 '',
 '',
 '',
 ',',
 "''",
 ".6''",
 ",',",
 '',
 "'''",
 "''",
 '&',
 '250,000',
 "'''—'",
 '',
 '‘’',
 ',',
 '-',
 "''&'",
 '-é',
 '‘-’',
 "-'",
 '’',
 '',
 '?',
 '-',
 '’‘’',
 "'-",
 ':—',
 "':''",
 '2',
 "''-",
 '-19',
 '',
 ',',
 '2',
 "''",
 '',
 '',
 ":''",
 '1026',
 '',
 ':-..',
 "',",
 '10',
 ',--',
 "'-1",
 ',',
 '',
 ',',
 ',..:',
 '',
 '-',
 '',
 '',
 ",''",
 '-19',
 '’:',
 '13$130',
 "-'''",
 '-2024',
 "'",
 "'",
 "''''",
 "''",
 '',
 "'",
 '..',
 ',',
 '!.',
 '12019',
 '--',
 "'",
 ':',
 ',',
 "''''",
 '',
 '‘’',
 "'115-114",
 "''",
 ',',
 '',
 '14',
 '',
 ',',
 ',21,3',
 ',4-,65',
 '',
 "'50",
 ',-',
 '',
 '',
 '100%',
 '..',
 '-1/6',
 '-19',
 "''",
 '30',
 '',
 "':''",
 '?',
 "’'-'.’.",
 '',
 '$800',
 '$30',
 '.6',
 "..''",
 '',
 ',',
 '',
 "''",
 ',',
 ',--,',
 '',
 "'''','-'",
 "'",
 '&',
 "''-",
 ":'",
 '',
 '',
 "-'''",
 '3',
 '',
 '',
 '.2',
 "''",
 '’',
 ".'",
 '‘’',
 "-‘'",
 '-’‘’',
 '...',
 "',",
 '4',
 '..',
 '',
 "-''",
 "'''",
 '9',
 '.6101',
 ":''",
 '’‘’',
 ".'-'",
 '',
 '.,,',
 '',
 ',,',
 '‘’:..',
 '',
 "''''",
 "''''&'-''",
 ':‘’',
 '2022:,',
 '',
 '..',
 "'",
 "'''",
 '',
 "''",
 "--:'''",
 ',,100',
 '',
 ',',
 '',
 "'",
 "?'.",
 '5-',
 '',
 "-''",
 '-......',
 '',
 "'",
 '’',
 '-',
 "':''",
 '-’’',
 '‘’',
 '50',
 "''",
 '‘’',
 '’',
 "'**'''",
 "''''",
 '',
 '',
 "':‘’",
 '$100',
 ".'",
 "''-’''",
 '2022:',
 '-',
 ":'','",
 ".:'''",
 '‘’..',
 ":''",
 "'''",
 '..',
 '60,',
 "'",
 "'",
 '..,..',
 ",'",
 '.,',
 "''''",
 '!.',
 "''",
 '',
 '',
 '-6',
 '',
 '',
 '..',
 '’,',
 ':',
 '2',
 '9',
 "''.6",
 '9',
 "''",
 '',
 '',
 "1.5','",
 '70-',
 '',
 '‘,’.1,$300',
 '4',
 '.6‘’',
 '-',
 '‘’',
 "'':",
 '',
 '',
 '',
 '',
 "',''",
 '4..',
 '-',
 "''",
 '',
 "',1",
 '4,107',
 '9,2',
 ...]

In [46]:
df.loc[1,'headline']

'American Airlines Flyer Charged, Banned For Life After Punching Flight Attendant On Video'