<a href="https://colab.research.google.com/github/Karthik5412/News-Classifier/blob/master/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import nltk as nl
import matplotlib.pyplot as plt
import seaborn

In [ ]:
bussiness = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/business_data.csv')

education = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/education_data.csv')

entertainment = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/entertainment_data.csv')

sports = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/sports_data.csv')

technology = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/technology_data.csv')

In [ ]:
df = pd.concat([bussiness, education, entertainment, sports, technology], axis= 0)

df = df.sample(frac= 1).reset_index(drop= True)

df

,headlines,description,content,url,category
0,FA Cup: Brighton look to end Liverpool’s Cup run,Underperforming Klopp's side travel to Amex St...,"Brighton vs Liverpool (FA Cup 4th Round, Sunda...",https://indianexpress.com/article/sports/footb...,sports
1,Microsoft’s OpenAI investment risks EU merger ...,Microsoft last year committed to invest over $...,Microsoft’s financial backing for ChatGPT make...,https://indianexpress.com/article/technology/t...,technology
2,Punjab schools to reopen today: State educatio...,"Earlier, the Punjab government had ordered cl...",The Punjab government on Sunday announced that...,https://indianexpress.com/article/education/pu...,education
3,Card & internet frauds rise sharply: RBI data,"On the other hand, based on the date of occurr...","Based on the date of reporting, the average am...",https://indianexpress.com/article/business/ban...,business
4,"Alia Bhatt is in the limelight at GQ event, re...","Alia Bhatt, Karan Johar, Shahid Kapoor, Sunny ...",Alia Bhatt made a very stylish and bold outing...,https://indianexpress.com/article/entertainmen...,entertainment
...,...,...,...,...,...
9995,Don’t like home sides denying touring teams qu...,"Healy backed Khawaja's suggestion, saying it w...",Legendary Australian wicket-keeper Ian Healy h...,https://indianexpress.com/article/sports/crick...,sports
9996,‘India is in very good hands’: Michael Douglas...,Michael Douglas is being conferred with the pr...,American actor and film producer Michael Dougl...,https://indianexpress.com/article/entertainmen...,entertainment
9997,IIT Jodhpur launches specialised MBA programme...,Interested candidates can visit the official w...,"The Indian Institute of Technology (IIT), Jodh...",https://indianexpress.com/article/education/ii...,education
9998,"Q3 Results: IOC, DLF, Bajaj Auto, TVS Motor re...",Q3 Results: Most companies managed their perfo...,Investors will continue their focus on earning...,https://indianexpress.com/article/business/com...,business
9999,Senators demand documents from Meta on social ...,The letter follows a hearing with a new whistl...,A bipartisan group of U.S. Senators has writte...,https://indianexpress.com/article/technology/t...,technology

In [ ]:
df['category'].value_counts()

category
sports           2000
technology       2000
education        2000
business         2000
entertainment    2000
Name: count, dtype: int64

In [ ]:
df.isna().sum()

headlines      0
description    0
content        0
url            0
category       0
dtype: int64

In [ ]:
df.shape

(10000, 5)

In [ ]:
df = df.drop_duplicates()
df.shape

(10000, 5)

In [ ]:
df

,headlines,description,content,url,category
0,FA Cup: Brighton look to end Liverpool’s Cup run,Underperforming Klopp's side travel to Amex St...,"Brighton vs Liverpool (FA Cup 4th Round, Sunda...",https://indianexpress.com/article/sports/footb...,sports
1,Microsoft’s OpenAI investment risks EU merger ...,Microsoft last year committed to invest over $...,Microsoft’s financial backing for ChatGPT make...,https://indianexpress.com/article/technology/t...,technology
2,Punjab schools to reopen today: State educatio...,"Earlier, the Punjab government had ordered cl...",The Punjab government on Sunday announced that...,https://indianexpress.com/article/education/pu...,education
3,Card & internet frauds rise sharply: RBI data,"On the other hand, based on the date of occurr...","Based on the date of reporting, the average am...",https://indianexpress.com/article/business/ban...,business
4,"Alia Bhatt is in the limelight at GQ event, re...","Alia Bhatt, Karan Johar, Shahid Kapoor, Sunny ...",Alia Bhatt made a very stylish and bold outing...,https://indianexpress.com/article/entertainmen...,entertainment
...,...,...,...,...,...
9995,Don’t like home sides denying touring teams qu...,"Healy backed Khawaja's suggestion, saying it w...",Legendary Australian wicket-keeper Ian Healy h...,https://indianexpress.com/article/sports/crick...,sports
9996,‘India is in very good hands’: Michael Douglas...,Michael Douglas is being conferred with the pr...,American actor and film producer Michael Dougl...,https://indianexpress.com/article/entertainmen...,entertainment
9997,IIT Jodhpur launches specialised MBA programme...,Interested candidates can visit the official w...,"The Indian Institute of Technology (IIT), Jodh...",https://indianexpress.com/article/education/ii...,education
9998,"Q3 Results: IOC, DLF, Bajaj Auto, TVS Motor re...",Q3 Results: Most companies managed their perfo...,Investors will continue their focus on earning...,https://indianexpress.com/article/business/com...,business
9999,Senators demand documents from Meta on social ...,The letter follows a hearing with a new whistl...,A bipartisan group of U.S. Senators has writte...,https://indianexpress.com/article/technology/t...,technology

In [ ]:
# Dropping unwanted columns for this

df = df.drop(columns= ['url'])
df_copy = df.copy()
df

,headlines,description,content,category
0,FA Cup: Brighton look to end Liverpool’s Cup run,Underperforming Klopp's side travel to Amex St...,"Brighton vs Liverpool (FA Cup 4th Round, Sunda...",sports
1,Microsoft’s OpenAI investment risks EU merger ...,Microsoft last year committed to invest over $...,Microsoft’s financial backing for ChatGPT make...,technology
2,Punjab schools to reopen today: State educatio...,"Earlier, the Punjab government had ordered cl...",The Punjab government on Sunday announced that...,education
3,Card & internet frauds rise sharply: RBI data,"On the other hand, based on the date of occurr...","Based on the date of reporting, the average am...",business
4,"Alia Bhatt is in the limelight at GQ event, re...","Alia Bhatt, Karan Johar, Shahid Kapoor, Sunny ...",Alia Bhatt made a very stylish and bold outing...,entertainment
...,...,...,...,...
9995,Don’t like home sides denying touring teams qu...,"Healy backed Khawaja's suggestion, saying it w...",Legendary Australian wicket-keeper Ian Healy h...,sports
9996,‘India is in very good hands’: Michael Douglas...,Michael Douglas is being conferred with the pr...,American actor and film producer Michael Dougl...,entertainment
9997,IIT Jodhpur launches specialised MBA programme...,Interested candidates can visit the official w...,"The Indian Institute of Technology (IIT), Jodh...",education
9998,"Q3 Results: IOC, DLF, Bajaj Auto, TVS Motor re...",Q3 Results: Most companies managed their perfo...,Investors will continue their focus on earning...,business
9999,Senators demand documents from Meta on social ...,The letter follows a hearing with a new whistl...,A bipartisan group of U.S. Senators has writte...,technology

### Making Pipeline

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
import re
import string

class processing(BaseEstimator,TransformerMixin) :
    def fit(self, x, y=None ) :
        return self

    def healper(self, x):
        x = re.sub(r'[^a-zA-z\s]','',x.lower())
        return ' '.join(x.split())

    def transform(self, x) :
        combined = (x['headlines'].astype(str) + ' ' +
                    x['description'].astype(str) + ' ' +
                    x['content'].astype(str))

        return combined.apply(self.healper).tolist()

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

text_pipe = Pipeline([
    ('Text',processing()),
    ('Vectorizer', TfidfVectorizer(stop_words='english'))
])

prep_pipe = ColumnTransformer([
    ('Processing', text_pipe,['headlines', 'description', 'content'])
], remainder= 'passthrough')

pipe = Pipeline([
    ('preprocessing', prep_pipe),
    ('Classifier', LogisticRegression(max_iter= 1000, class_weight= 'balanced'))
])

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['enc'] = le.fit_transform(df['category'])

In [ ]:
df['enc'].value_counts()

enc
3    2000
4    2000
1    2000
0    2000
2    2000
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['category', 'enc']), df['enc'], test_size= 0.33, random_state= 42)

In [ ]:
x_train

,headlines,description,content
8371,How Samsung is redefining shopping experience ...,"At Samsung BKC, one can experience cutting-edg...",Samsung unveiled its first O2O (online-to-offl...
5027,Elon Musk tests Twitch like live video game st...,Elon Musk recently shared about an hour long o...,X recently introduced a new feature that lets ...
9234,UGC opposes plea in Delhi HC against CLAT-base...,The Centre said in its response that DU was on...,CUET: The five-year law course is a profession...
3944,"Prabhas calls his mom his best critic, reveals...",Despite the overwhelming response from fans on...,Following a series of high-profile flops inclu...
6862,"‘Ranbir Kapoor’s eyes do the talking, Kangana ...",Anshul Chahuan was seen in Kangana Ranaut's Te...,"Actor Anshul Chauhan, who recently appeared in..."
...,...,...,...
5734,Adarsh Gourav worked with Shah Rukh Khan in My...,Adarsh Gourav said that even though he played ...,"Actor Adarsh Gourav, who was recently seen in ..."
5191,MP Board 12th Result 2023: Meritorious student...,MPBSE 12th Result 2023: Students can check the...,MPBSE MP Board Class 12th Result 2023 Updates:...
5390,Novak Djokovic slams TV channel for ‘judgement...,"The video, posted as an Instagram reel, shows ...",Novak Djokovic took issue with a social media ...
860,What if we could all control AI?,Opening up AI governance could increase societ...,Written by Kevin Roose\nOne of the fiercest de...
7270,While You Were Asleep: Ancelotti slams attacks...,Juventus won at Salernitana in Serie A and tha...,Real Madrid coach Carlo Ancelotti criticized t...

In [ ]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Processing',
                                                  Pipeline(steps=[('Text',
                                                                   processing()),
                                                                  ('Vectorizer',
                                                                   TfidfVectorizer(stop_words='english'))]),
                                                  ['headlines', 'description',
                                                   'content'])])),
                ('Classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [ ]:
pred = pipe.predict(x_test)

In [ ]:
y_test

6252    3
4684    2
1731    0
4742    3
4521    4
       ..
1744    0
9754    3
6094    2
8781    0
9401    4
Name: enc, Length: 3300, dtype: int64

In [ ]:
pred

array([3, 2, 0, ..., 2, 0, 4])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

acc = accuracy_score(y_true= y_test, y_pred= pred)

acc

0.9839393939393939

In [ ]:
pipe.score(x_train, y_train)

0.9944776119402985

In [ ]:
pipe.score(x_test, y_test)

0.9839393939393939

In [ ]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97       640
           1       1.00      0.99      0.99       696
           2       1.00      1.00      1.00       689
           3       0.99      0.99      0.99       646
           4       0.96      0.97      0.96       629

    accuracy                           0.98      3300
   macro avg       0.98      0.98      0.98      3300
weighted avg       0.98      0.98      0.98      3300

In [ ]:
import joblib

joblib.dump(pipe, 'Pipeline.plk')

['Pipeline.plk']