<a href="https://colab.research.google.com/github/Karthik5412/News-Classifier/blob/master/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries

In [151]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [152]:
import pandas as pd
import numpy as np
import nltk as nl
import matplotlib.pyplot as plt
import seaborn

In [153]:
bussiness = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/business_data.csv')

education = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/education_data.csv')

entertainment = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/entertainment_data.csv')

sports = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/sports_data.csv')

technology = pd.read_csv('/content/drive/MyDrive/news classifier/Datasets/technology_data.csv')

In [154]:
df = pd.concat([bussiness, education, entertainment, sports, technology], axis= 0)

df = df.sample(frac= 1).reset_index(drop= True)

df

,headlines,description,content,url,category
0,Alia Bhatt cheers for husband Ranbir Kapoor af...,The trailer of Ranbir Kapoor's upcoming film A...,Actor Alia Bhatt is highly impressed by the tr...,https://indianexpress.com/article/entertainmen...,entertainment
1,UGC removes Meghalaya’s Techno Global Universi...,"The Techno Global University, Shillong Polytec...","The Techno Global University, Shillong Polytec...",https://indianexpress.com/article/education/ug...,education
2,Redmi 13C 5G review: Recycling the affordable ...,"At Rs 10,999, the phone costs dangerously clos...",The budget smartphone market in India is heati...,https://indianexpress.com/article/technology/t...,technology
3,Shoaib Akhtar sees Shadab Khan as the next Pak...,The former Pakistan pacer had criticised Babar...,While former Pakistani speedster Shoaib Akhtar...,https://indianexpress.com/article/sports/crick...,sports
4,SEBI increases accountability of MF trustees,"While refusing to extend the time, the Delhi H...","In a setback for low-cost airline, SpiceJet, t...",https://indianexpress.com/article/business/avi...,business
...,...,...,...,...,...
9995,Ranbir Kapoor’s Animal gets adults only certif...,Animal marks the first collaboration between R...,The Animal is coming. Ranbir Kapoor’s latest a...,https://indianexpress.com/article/entertainmen...,entertainment
9996,Google year in search 2023: Kiara Advani most ...,Kiara Advani and Sidharth Malhotra landed in m...,Google year in search 2023: Kiara Advani tops ...,https://indianexpress.com/article/entertainmen...,entertainment
9997,Luxurious Living Redefined: Mеrlin Group annou...,Nestled in the heart of thе vibrant Banеr neig...,Following the resounding success of its luxuri...,https://indianexpress.com/article/business/spo...,business
9998,Rajkumar Hirani reveals why he didn’t want to ...,Did you know that the role of Sukhi in Dunki l...,"Amid the mixed response that his latest film, ...",https://indianexpress.com/article/entertainmen...,entertainment
9999,Katrina Kaif reveals how ‘green flag’ husband ...,Katrina Kaif and Vicky Kaushal sometimes have ...,Actor couple Katrina Kaif and Vicky Kaushal ha...,https://indianexpress.com/article/entertainmen...,entertainment

In [155]:
df['category'].value_counts()

category
entertainment    2000
education        2000
technology       2000
sports           2000
business         2000
Name: count, dtype: int64

In [156]:
df.isna().sum()

headlines      0
description    0
content        0
url            0
category       0
dtype: int64

In [157]:
df.shape

(10000, 5)

In [158]:
df = df.drop_duplicates()
df.shape

(10000, 5)

In [159]:
df

,headlines,description,content,url,category
0,Alia Bhatt cheers for husband Ranbir Kapoor af...,The trailer of Ranbir Kapoor's upcoming film A...,Actor Alia Bhatt is highly impressed by the tr...,https://indianexpress.com/article/entertainmen...,entertainment
1,UGC removes Meghalaya’s Techno Global Universi...,"The Techno Global University, Shillong Polytec...","The Techno Global University, Shillong Polytec...",https://indianexpress.com/article/education/ug...,education
2,Redmi 13C 5G review: Recycling the affordable ...,"At Rs 10,999, the phone costs dangerously clos...",The budget smartphone market in India is heati...,https://indianexpress.com/article/technology/t...,technology
3,Shoaib Akhtar sees Shadab Khan as the next Pak...,The former Pakistan pacer had criticised Babar...,While former Pakistani speedster Shoaib Akhtar...,https://indianexpress.com/article/sports/crick...,sports
4,SEBI increases accountability of MF trustees,"While refusing to extend the time, the Delhi H...","In a setback for low-cost airline, SpiceJet, t...",https://indianexpress.com/article/business/avi...,business
...,...,...,...,...,...
9995,Ranbir Kapoor’s Animal gets adults only certif...,Animal marks the first collaboration between R...,The Animal is coming. Ranbir Kapoor’s latest a...,https://indianexpress.com/article/entertainmen...,entertainment
9996,Google year in search 2023: Kiara Advani most ...,Kiara Advani and Sidharth Malhotra landed in m...,Google year in search 2023: Kiara Advani tops ...,https://indianexpress.com/article/entertainmen...,entertainment
9997,Luxurious Living Redefined: Mеrlin Group annou...,Nestled in the heart of thе vibrant Banеr neig...,Following the resounding success of its luxuri...,https://indianexpress.com/article/business/spo...,business
9998,Rajkumar Hirani reveals why he didn’t want to ...,Did you know that the role of Sukhi in Dunki l...,"Amid the mixed response that his latest film, ...",https://indianexpress.com/article/entertainmen...,entertainment
9999,Katrina Kaif reveals how ‘green flag’ husband ...,Katrina Kaif and Vicky Kaushal sometimes have ...,Actor couple Katrina Kaif and Vicky Kaushal ha...,https://indianexpress.com/article/entertainmen...,entertainment

In [160]:
# Dropping unwanted columns for this

df = df.drop(columns= ['url'])
df_copy = df.copy()
df

,headlines,description,content,category
0,Alia Bhatt cheers for husband Ranbir Kapoor af...,The trailer of Ranbir Kapoor's upcoming film A...,Actor Alia Bhatt is highly impressed by the tr...,entertainment
1,UGC removes Meghalaya’s Techno Global Universi...,"The Techno Global University, Shillong Polytec...","The Techno Global University, Shillong Polytec...",education
2,Redmi 13C 5G review: Recycling the affordable ...,"At Rs 10,999, the phone costs dangerously clos...",The budget smartphone market in India is heati...,technology
3,Shoaib Akhtar sees Shadab Khan as the next Pak...,The former Pakistan pacer had criticised Babar...,While former Pakistani speedster Shoaib Akhtar...,sports
4,SEBI increases accountability of MF trustees,"While refusing to extend the time, the Delhi H...","In a setback for low-cost airline, SpiceJet, t...",business
...,...,...,...,...
9995,Ranbir Kapoor’s Animal gets adults only certif...,Animal marks the first collaboration between R...,The Animal is coming. Ranbir Kapoor’s latest a...,entertainment
9996,Google year in search 2023: Kiara Advani most ...,Kiara Advani and Sidharth Malhotra landed in m...,Google year in search 2023: Kiara Advani tops ...,entertainment
9997,Luxurious Living Redefined: Mеrlin Group annou...,Nestled in the heart of thе vibrant Banеr neig...,Following the resounding success of its luxuri...,business
9998,Rajkumar Hirani reveals why he didn’t want to ...,Did you know that the role of Sukhi in Dunki l...,"Amid the mixed response that his latest film, ...",entertainment
9999,Katrina Kaif reveals how ‘green flag’ husband ...,Katrina Kaif and Vicky Kaushal sometimes have ...,Actor couple Katrina Kaif and Vicky Kaushal ha...,entertainment

### Making Pipeline

In [161]:
from sklearn.base import BaseEstimator, TransformerMixin
import re
import string

class processing(BaseEstimator,TransformerMixin) :
    def fit(self, x, y=None ) :
        return self

    def healper(self, x):
        x = re.sub(r'[^a-zA-z\s]','',x.lower())
        return ' '.join(x.split())

    def transform(self, x) :
        combined = (x['headlines'].astype(str) + ' ' +
                    x['description'].astype(str) + ' ' +
                    x['content'].astype(str))

        return combined.apply(self.healper).tolist()

In [162]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

text_pipe = Pipeline([
    ('Text',processing()),
    ('Vectorizer', TfidfVectorizer(stop_words='english'))
])

prep_pipe = ColumnTransformer([
    ('Processing', text_pipe,['headlines', 'description', 'content'])
], remainder= 'passthrough')

pipe = Pipeline([
    ('preprocessing', prep_pipe),
    ('Classifier', LogisticRegression(max_iter= 1000, class_weight= 'balanced'))
])

In [163]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['enc'] = le.fit_transform(df['category'])

In [164]:
df['enc'].value_counts()

enc
2    2000
1    2000
4    2000
3    2000
0    2000
Name: count, dtype: int64

In [165]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['category', 'enc']), df['enc'], test_size= 0.33, random_state= 42)

In [166]:
x_train

,headlines,description,content
8371,I feel he should be given one more chance: Sun...,IND vs AUS: Another former India player Madan ...,IND vs AUS: India legend Sunil Gavaskar has ba...
5027,Current account deficit in April-June narrows ...,The widening of CAD on a quarter-on-quarter ba...,India’s current account deficit (CAD) narrowed...
9234,Popular online chat website Omegle shuts down ...,"Omegle, the popular online chat website that l...","Omegle, a popular website that allowed people ..."
3944,What ails India’s women’s hockey team: No big ...,"The triumph at the Asian Champions Trophy, a p...","“I don’t know.”\nWith these words, India coach..."
6862,Markets decline in early trade on weak global ...,"Rallying for the third day, the Sensex climbed...",Equity benchmark indices declined in early tra...
...,...,...,...
5734,‘Why humanities courses are integral – not sup...,"""Whereas engineers are taught to think in term...",(A Lesson from IIT is a weekly column by an II...
5191,When Karan Johar surprised Shah Rukh Khan by c...,"Recently, Karan Johar revisited shooting one o...","To this day, Karan Johar’s directorial debut f..."
5390,India among eight direct qualifiers for Women’...,The top-three teams from each group of the rec...,"India, by virtue of finishing inside the top-t..."
860,Consumerware player Cello World sets IPO price...,The issue will open for public subscription on...,Household products and stationery manufacturer...
7270,"‘Shaheen bahot accha hai, Bumrah toh uske paas...",Both Afridi and Bumrah have been out of action...,Shaheen Shah Afridi and Jasprit Bumrah share 5...

In [167]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Processing',
                                                  Pipeline(steps=[('Text',
                                                                   processing()),
                                                                  ('Vectorizer',
                                                                   TfidfVectorizer(stop_words='english'))]),
                                                  ['headlines', 'description',
                                                   'content'])])),
                ('Classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [168]:
pred = pipe.predict(x_test)

In [169]:
y_test

6252    2
4684    3
1731    1
4742    1
4521    2
       ..
1744    0
9754    4
6094    4
8781    1
9401    3
Name: enc, Length: 3300, dtype: int64

In [170]:
pred

array([2, 3, 1, ..., 4, 1, 3])

In [171]:
from sklearn.metrics import accuracy_score, classification_report

acc = accuracy_score(y_true= y_test, y_pred= pred)

acc

0.9812121212121212

In [172]:
pipe.score(x_train, y_train)

0.9943283582089553

In [173]:
pipe.score(x_test, y_test)

0.9812121212121212

In [174]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       656
           1       0.99      0.98      0.99       669
           2       1.00      0.99      0.99       669
           3       0.99      0.99      0.99       665
           4       0.96      0.97      0.96       641

    accuracy                           0.98      3300
   macro avg       0.98      0.98      0.98      3300
weighted avg       0.98      0.98      0.98      3300